#+BEGIN_HTML
---
layout: post
title: To Be A Better Man
subtitle: "Send someone to love me I need to rest in arms"
date: 2016-12-31
categories: [Writing]
tags: [Logging, Someone]
---
#+END_HTML

很奇幻奇妙并且忐忑的一周终于过去了，一年将尽。

** 人生就是一连串的死亡与复活
- 这一周过的，在水火之中奔走。在作业缠身的情况下，又根本无法抑制想腻在一起的渴望，这种感觉，真是爽。不想看代码，只想看你。不想要作业，只想要你。

- 手， 要好好保养了，要靠他干很多事情。比如，牵着你。

- 已经记得你的味道，记得你手的温度，记得走过的校园路，记得你的笑和可爱模样。

- 继续做自己，To Be A Better Man。

- 你是我的一颗糖。

- 一直觉得自己的运气不怎么好，总会有不顺利的事情发生。直到遇见你才明白可能我的运气都用来遇见你了吧。

- 图书馆虽然很小，但是很有味道，狭小的空间，满眼想看的书，满脑子想着的你。

- 坐在一起上了2016的最后一堂课。

- 小小的爱，在大大的城市里。甜蜜自知

- 你想要星星，我要怎么摘给你。因为路途遥远，我怕没人在地球陪你。

- 想要学习的东西都可以为你展示，想要给你看我走来的路，想要以后的路上有你。喜欢听你分享你的故事，那样我可以想象我们只是重逢。是否会在你的名字前面注上我姓氏。

- 喜欢摸你的头发，因为那是一种你在手心的感觉，捧你的脸同理可证。

- 看不清我的时候，走近一点:P

- 外边天很冷，其实很想把你裹到大衣里:P


** See You Tomorrow
去看了电影摆渡人，还能记得当时同学推荐我看《从你的全世界路过》的时候，我心中不屑的感觉。这种情爱纠缠与我何干。可谁知看上之后却深陷其中，不知
真实中，是否张嘉佳真的有这样那样神奇的朋友。听说将被拍成电影，遂期待，不知不觉竟然已经上映。可见有些事情还是不要老惦记着，该忘就忘，转角就会
遇到惊喜。是吗？

梁朝伟，金城武，陈奕迅不得不说是八零后的集体回忆了吧，随着八零后在社会上慢慢站稳，生活走上轨道，集体怀旧这几年很热闹。这部电影可以说是大杂烩，
写着王家卫监制，有着浓烈的他的风格，梁朝伟和金城武也算花样年华和阿飞正传的混杂，奇怪为啥没有张曼玉。电影前半段略显无聊，中间往后才开始情节的
起伏，为情所困的人呀，我来了，我累了，我走了，说出了很多人的心声。摆渡人必须先摆渡自己，那就是喝酒。我是不喜欢这种方式的，在酒精中得不到任何。
我只愿与我爱的人醉～

我现在看电影不再像以前有所目的，希望能收获什么东西。何必呢，人生很多事情就是没有意义的或许说是，他们的意义并不受常规的评判标准。否则认为全然
没有意义的人是虚无主义的人。浪费时间和荒废青春，只要开心就好，只要找到认为对的人就好。在情节中沉醉，有所感动，有所唏嘘，就好了。电影中，虽然
过去一周，回想起来，有两个情节现在还能想起来：一个是小玉趁着马力睡着在阳光下用影子拥抱他。一个是在摆渡李宇春饰演的那个女孩的时候把冰喻缘。


** Plan
研究生的上学期就随着查完OOP的作业结束了，终于可以肆无忌惮的做自己想做的事情了。



#+BEGIN_HTML
<!-- more-forword -->
#+END_HTML


#+BEGIN_HTML
<!-- more -->
#+END_HTML
